
spring:
    profiles:
        active: dev
    devtools:
        restart:
            enabled: true
    datasource:
        type: com.zaxxer.hikari.HikariDataSource
        url: jdbc:h2:mem:votacao;DB_CLOSE_DELAY=-1
        username: risk
        password: risk
    h2:
        console:
            enabled: false
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        database: H2
        show-sql: true
        
liquibase:
    contexts: dev
    
server:
    port: 8080
